ID   AQP1_HUMAN     STANDARD;      PRT;   269 AA.
AC   P29972;
DT   01-APR-1993 (Rel. 25, Created)
DT   01-APR-1993 (Rel. 25, Last sequence update)
DT   15-JUL-1998 (Rel. 36, Last annotation update)
DE   AQUAPORIN-CHIP (WATER CHANNEL PROTEIN FOR RED BLOOD CELLS AND KIDNEY
DE   PROXIMAL TUBULE) (AQUAPORIN 1) (URINE WATER CHANNEL).
GN   AQP1 OR CHIP28.
OS   Homo sapiens (Human).
OC   Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Mammalia;
OC   Eutheria; Primates; Catarrhini; Hominidae; Homo.
RN   [1]
RP   SEQUENCE FROM N.A., AND PARTIAL SEQUENCE.
RX   MEDLINE; 92107900.
RA   PRESTON G.M., AGRE P.;
RT   "Isolation of the cDNA for erythrocyte integral membrane protein of
RT   28 kilodaltons: member of an ancient channel family.";
RL   Proc. Natl. Acad. Sci. U.S.A. 88:11110-11114(1991).
RN   [2]
RP   SEQUENCE FROM N.A.
RX   MEDLINE; 93340184.
RA   MOON C., PRESTON G.M., GRIFFIN C.A., JABS E.W., AGRE P.;
RT   "The human aquaporin-CHIP gene. Structure, organization, and
RT   chromosomal localization.";
RL   J. Biol. Chem. 268:15772-15778(1993).
RN   [3]
RP   SEQUENCE FROM N.A.
RC   TISSUE=RETINA;
RA   RUIZ A.C., BOK D.;
RL   Submitted (MAY-1996) to the EMBL/GenBank/DDBJ databases.
RN   [4]
RP   SEQUENCE FROM N.A.
RC   TISSUE=UTERUS;
RX   MEDLINE; 94290349.
RA   LI X., YU H., KOIDE S.S.;
RT   "The water channel gene in human uterus.";
RL   Biochem. Mol. Biol. Int. 32:371-377(1994).
RN   [5]
RP   FUNCTION.
RX   MEDLINE; 92229472.
RA   PRESTON G.M., CARROLL T.P., GUGGINO W.B., AGRE P.;
RT   "Appearance of water channels in Xenopus oocytes expressing red cell
RT   CHIP28 protein.";
RL   Science 256:385-387(1992).
RN   [6]
RP   TARGET OF MERCURY INHIBITION.
RX   MEDLINE; 93106996.
RA   PRESTON G.M., JUNG J.S., GUGGINO W.B., AGRE P.;
RT   "The mercury-sensitive residue at cysteine 189 in the CHIP28 water
RT   channel.";
RL   J. Biol. Chem. 268:17-20(1993).
RN   [7]
RP   TOPOLOGY.
RX   MEDLINE; 94124503.
RA   PRESTON G.M., JUNG J.S., GUGGINO W.B., AGRE P.;
RT   "Membrane topology of aquaporin CHIP. Analysis of functional epitope-
RT   scanning mutants by vectorial proteolysis.";
RL   J. Biol. Chem. 269:1668-1673(1994).
RN   [8]
RP   STRUCTURE BY ELECTRON CRYO-MICROSCOPY.
RX   MEDLINE; 94313979.
RA   WALZ T., SMITH B.L., AGRE P., ENGEL A.;
RT   "The three-dimensional structure of human erythrocyte aquaporin
RT   CHIP.";
RL   EMBO J. 13:2985-2993(1994).
RN   [9]
RP   STRUCTURE BY ELECTRON CRYO-MICROSCOPY.
RX   MEDLINE; 97320502.
RA   WALZ T., HIRAI T., MURATA K., HEYMANN J.B., MITSUOKA K.,
RA   FUJIYOSHI Y., SMITH B.L., AGRE P., ENGEL A.;
RT   "The three-dimensional structure of aquaporin-1.";
RL   Nature 387:624-627(1997).
RN   [10]
RP   VARIANT BLOOD GROUP COLTON.
RX   MEDLINE; 94365170.
RA   SMITH B.L., PRESTON G.M., SPRING F., ANSTEE D.J., AGRE P.;
RT   "Human red cell aquaporin CHIP. I. Molecular characterization of ABH
RT   and Colton blood group antigens.";
RL   J. Clin. Invest. 94:1043-1049(1994).
CC   -!- FUNCTION: FORMS A WATER-SPECIFIC CHANNEL THAT PROVIDES THE PLASMA
CC       MEMBRANES OF RED CELLS AND KIDNEY PROXIMAL TUBULES WITH HIGH
CC       PERMEABILITY TO WATER, THEREBY PERMITTING WATER TO MOVE IN THE
CC       DIRECTION OF AN OSMOTIC GRADIENT.
CC   -!- SUBUNIT: HOMOTETRAMER.
CC   -!- SUBCELLULAR LOCATION: INTEGRAL MEMBRANE PROTEIN.
CC   -!- TISSUE SPECIFICITY: ERYTHROCYTES AND RENAL TUBULES.
CC   -!- POLYMORPHISM: AQP1 IS RESPONSIBLE FOR THE COLTON BLOOD GROUP
CC       SYSTEM. APPROXIMATELY 92% OF CAUCASIANS ARE CO(A+B-) (ALA-45),
CC       APPROXIMATELY 8% ARE CO(A+B+), AND ONLY 0.2% ARE CO(A-B+) (VAL-
CC       45). CO(A-B-) WHICH IS VERY RARE, IS DUE TO A COMPLETE ABSENCE OF
CC       AQP1.
CC   -!- MISCELLANEOUS: PHARMACOLOGICALLY INHIBITED BY SUBMILLIMOLAR
CC       CONCENTRATIONS OF HG2+.
CC   -!- SIMILARITY: BELONGS TO THE TRANSMEMBRANE CHANNEL MIP FAMILY.
CC   --------------------------------------------------------------------------
CC   This SWISS-PROT entry is copyright. It is produced through a collaboration
CC   between  the Swiss Institute of Bioinformatics  and the  EMBL outstation -
CC   the European Bioinformatics Institute.  There are no  restrictions on  its
CC   use  by  non-profit  institutions as long  as its content  is  in  no  way
CC   modified and this statement is not removed.  Usage  by  and for commercial
CC   entities requires a license agreement (See http://www.isb-sib.ch/announce/
CC   or send an email to license@isb-sib.ch).
CC   --------------------------------------------------------------------------
DR   EMBL; M77829; AAA58425.1; -.
DR   EMBL; U41517; AAC50648.1; -.
DR   EMBL; S73482; AAB31193.1; -.
DR   PIR; A41616; A41616.
DR   MIM; 107776; -.
DR   MIM; 110450; -.
DR   PFAM; PF00230; MIP; 1.
DR   PROSITE; PS00221; MIP; 1.
KW   Transport; Transmembrane; Polymorphism; Blood group antigen.
FT   DOMAIN        1     14       CYTOPLASMIC (POTENTIAL).
FT   TRANSMEM     18     35       POTENTIAL.
FT   DOMAIN       36     48       EXTRACELLULAR (POTENTIAL).
FT   TRANSMEM     49     67       POTENTIAL.
FT   DOMAIN       68     93       CYTOPLASMIC (POTENTIAL).
FT   TRANSMEM     94    115       POTENTIAL.
FT   DOMAIN      116    135       EXTRACELLULAR (POTENTIAL).
FT   TRANSMEM    136    156       POTENTIAL.
FT   DOMAIN      157    164       CYTOPLASMIC (POTENTIAL).
FT   TRANSMEM    165    184       POTENTIAL.
FT   DOMAIN      185    210       EXTRACELLULAR (POTENTIAL).
FT   TRANSMEM    211    232       POTENTIAL.
FT   DOMAIN      233    269       CYTOPLASMIC (POTENTIAL).
FT   SITE        189    189       HG(2+)-SENSITIVE RESIDUE.
FT   DOMAIN      159    162       POLY-ARG.
FT   CARBOHYD     42     42       POTENTIAL.
FT   CARBOHYD    205    205       POTENTIAL.
FT   VARIANT      45     45       A -> V (IN CO(A-B+) ANTIGEN).
FT                                /FTId=VAR_004400.
SQ   SEQUENCE   269 AA;  28526 MW;  8063A7AD CRC32;
     MASEFKKKLF WRAVVAEFLA TTLFVFISIG SALGFKYPVG NNQTAVQDNV KVSLAFGLSI
     ATLAQSVGHI SGAHLNPAVT LGLLLSCQIS IFRALMYIIA QCVGAIVATA ILSGITSSLT
     GNSLGRNDLA DGVNSGQGLG IEIIGTLQLV LCVLATTDRR RRDLGGSAPL AIGLSVALGH
     LLAIDYTGCG INPARSFGSA VITHNFSNHW IFWVGPFIGG ALAVLIYDFI LAPRSSDLTD
     RVKVWTSGQV EEYDLDADDI NSRVEMKPK
//
